sudo: false

language: python

python:
  - "3.5"

services:
  - redis  # start redis
  - mysql  # start mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'pydatacoll'@'localhost' IDENTIFIED BY 'pydatacoll';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'pydatacoll'@'localhost';" -uroot

install:
  - pip install -r requirements.txt
  - pip install coveralls

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

script:
  - coverage run -m unittest

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5e23a948a5db4bd6c93f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
